### ISSUE TITLE
Todo App 완성

### ISSUE THREAD

**Issue by ko9612** [ko9612/Todo_App#1]
### 만들고자 하는 기능
Todo  App 완성 후, 배포

### 해당 기능을 구현하기 위해 할 일

- [x] Create : 투두 리스트가 생성되어야 합니다.
- [x] Read : 생성된 투두 리스트가 뷰로 보여야 합니다.
- [ ] Update : 생성된 투두 리스트를 수정할 수 있어야 합니다.
- [x]  Delete : 생성된 투두 리스트를 삭제할 수 있어야 합니다.

- [ ] Json server 재적용
- [ ] 배포 완료

### 예상 작업 시간 
3시간
